# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: faa0fa89db81b49418c93c1a2544f7286813c9e77aa6573a754c41642006727e758cd1aa04172a4d0072a07a58574bdbce6e0fbbfdee21ff1540deb5744e8689

test:
  secret_key_base: 2794e62c9952e86e00e903ee926535026a5b49c0fe642727567aaf35a07dea1e23d47a0fda6781a8cbbdc8a17a8ac811896f4dce3ddbe325a7eb8666e15a715a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
